se añadió links, routers y servicios
Standar-sazon/frontend_standar_sazon pull request #38
Opened 2021-03-14 15:36 UTC by arce2508

2021-03-15 16:56 UTC, EveFer commented on services/recipes.js
> +function recipeRequest (objectRecipes) {
```suggestion
function recipeRequest (token) {
```

2021-03-15 17:06 UTC, EveFer requested changes

2021-03-15 17:06 UTC, EveFer commented on services/recipes.js
> +}
Es un buen aproach, solo que verifica bien que es lo que necesitamos para obtener todos las recetas.

- No es necesario pasarle un objeto como parametro, más bien necesitariamos el token
- Los headers se modificarían, faltaría agregar el header de authoritation y pasarle el token

2021-03-15 17:06 UTC, EveFer commented on services/recipes.js
> +    },
```suggestion
    headers: {
      'content-Type': 'application/json',
      Authorization: `Bearer ${token}`
    },
```

2021-03-15 17:06 UTC, EveFer commented on services/recipes.js
> +}
De igual forma que es lo que se necesita para actualizar una receta.

- Se necesita el id de la receta a actualizar
- El objeto con la nueva data a actualizar de la receta
- El token

2021-03-15 17:06 UTC, EveFer commented on services/recipes.js
> +}
Lo mismo verifica que se necesita para eliminar:

- EL id de la receta a eliminar
- No es necesario el objeto
- El token

2021-03-16 01:21 UTC, arce2508 commented
listas las correcciones :)

2021-03-16 02:13 UTC, EveFer approved these changes

2021-03-16 02:13 UTC, EveFer commented on services/recipes.js
> +  const URL = `${(id, URL_BASE)}recipes`
```suggestion
  const URL = `${URL_BASE}recipes/${id}`
```

2021-03-16 02:14 UTC, Silver899 approved these changes

2021-03-16 02:14 UTC, merged